### ISSUE TITLE
it possible to find flag in this picture?

### ISSUE THREAD

**Issue by JohnNattakit** [d3k4z/writeups#1]
May I have some question please? is it possible to find flag in this picture? I have seen you extracted some data from this picture, Is it useful to deep in to flag or I'm wasting time to investigate this picture...
 https://github.com/d3k4z/writeups/blob/master/Gam3z_Inc/GGoCySEA_Mobile_Trackers.png

**Comment by d3k4z** [comment]
I am really sorry for the late reply , but there was no flag in the picture although it was quite big of a size.

**Comment by JohnNattakit** [comment]
I already resolved it thanks!!
